# Generated by Django 3.2.5 on 2021-07-18 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210718_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
